"""Add practice_mode as string to MockSession

Revision ID: 09f92f708602
Revises: 36bd6e344667
Create Date: 2025-07-26 04:23:53.967454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f92f708602'
down_revision: Union[str, Sequence[str], None] = '36bd6e344667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'mock_sessions',
        sa.Column(
            'practice_mode',
            sa.String(length=10),
            nullable=False,
            server_default='mcq'  # 🛠️ Use this to populate existing rows
        )
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_sessions', 'practice_mode')
    # ### end Alembic commands ###
